FROM rust:slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/target/release/rust_actix /app/rust_actix
EXPOSE 8080
CMD ["./rust_actix"]