FROM python:3.12-slim
WORKDIR /app
COPY . /app
RUN pip install django django-ninja gunicorn
RUN python3 manage.py migrate || true
CMD ["gunicorn", "-w", "4", "ninja_project.wsgi:application", "--bind", "0.0.0.0:8003", "--threads", "1", "--worker-connections", "1000"]