FROM python:3.12-slim

WORKDIR /app
COPY . /app
RUN pip install fastapi gunicorn uvicorn

CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8001", "--threads", "1", "--worker-connections", "1000"]