FROM rust:slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/target/release/rust_rocket /app/rust_rocket
EXPOSE 8000
CMD ["./rust_rocket", "--port", "8000"]