FROM rust:slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/target/release/rust_axum /app/rust_axum
EXPOSE 3000
CMD ["./rust_axum"]